### ISSUE TITLE
UTime crashing people with LUA Panic

### ISSUE THREAD

**Issue by dan-haynes** [TeamUlysses/utime#4]
### Steps to reproduce
1. Install UTime
2. Large playerbase I believe
3. No real way to reproduce it but it happens a lot to new players on the server. I currently have it fixed by just removing UTime so right now it is working fine without UTime

### Expected behavior
Player should load into the server and spawn with minimal lag

### Actual behavior
Player crashes on sending client info with the error LUA Panic Not enough memory

### Error(s) in server console, if any
Nothing

### Error(s) in player's console, if any
Cbuf_AddText: buffer overflow
Cbuf_AddText: buffer overflow

### Version
Tried with the 3 latest versions

**Comment by quickdude111** [comment]
```
    "utime_enable"      "1"
    "utime_outsidecolor_r"      "0"
    "utime_outsidecolor_g"      "150"
    "utime_outsidecolor_b"      "245"
    "utime_outsidetext_r"       "255"
    "utime_outsidetext_g"       "255"
    "utime_outsidetext_b"       "255"
    "utime_insidecolor_r"       "250"
    "utime_insidecolor_g"       "250"
    "utime_insidecolor_b"       "245"
    "utime_insidetext_r"        "0"
    "utime_insidetext_g"        "0"
    "utime_insidetext_b"        "0"
    "utime_pos_x"       "100.000000"
    "utime_pos_y"       "11.860000"
```
the workaround we've found besides removing the addon is to have the afflicted users add that to their clients client.vdf file inside their cfg folder within cvars.
for example,
```
"CVars"
{
	"utime_enable"      "1"
	"utime_outsidecolor_r"      "0"
	"utime_outsidecolor_g"      "150"
	"utime_outsidecolor_b"      "245"
	"utime_outsidetext_r"       "255"
	"utime_outsidetext_g"       "255"
	"utime_outsidetext_b"       "255"
	"utime_insidecolor_r"       "250"
	"utime_insidecolor_g"       "250"
	"utime_insidecolor_b"       "245"
	"utime_insidetext_r"        "0"
	"utime_insidetext_g"        "0"
	"utime_insidetext_b"        "0"
	"utime_pos_x"       "100.000000"
	"utime_pos_y"       "11.860000"
}
```

edit: On my vanilla server these lines were automatically added to the clients client.vdf file, but on the afflicted server it would not add them.

**Comment by sarahsturgeon** [comment]
> the workaround we've found besides removing the addon is to have the afflicted users add that to their clients client.vdf file inside their cfg folder within cvars.
> for example,
> 
> ```
> "CVars"
> {
> 	"utime_enable"      "1"
> 	"utime_outsidecolor_r"      "0"
> 	"utime_outsidecolor_g"      "150"
> 	"utime_outsidecolor_b"      "245"
> 	"utime_outsidetext_r"       "255"
> 	"utime_outsidetext_g"       "255"
> 	"utime_outsidetext_b"       "255"
> 	"utime_insidecolor_r"       "250"
> 	"utime_insidecolor_g"       "250"
> 	"utime_insidecolor_b"       "245"
> 	"utime_insidetext_r"        "0"
> 	"utime_insidetext_g"        "0"
> 	"utime_insidetext_b"        "0"
> 	"utime_pos_x"       "100.000000"
> 	"utime_pos_y"       "11.860000"
> }
> ```
> 
> edit: On my vanilla server these lines were automatically added to the clients client.vdf file, but on the afflicted server it would not add them.

Do you know which of those specifically helped? I can't imagine changing the colors would have an enormous impact on clientside memory usage?


To add to this issue: We've been experiencing frequent and numerous clientside timeouts for years now. We haven't been able to find the cause.

We just recently opened a DarkRP server and added Utime a few days after opening (UTime was the _only_ thing that was added or changed at that point). After restarting it was like a pandemic - easily 30% of players were timing out while, or shortly after loading in.

After analyzing the logs, we discovered that zero players timed out within 6 minutes of spawning from the time the server opened, to the point where we added UTime.

This continued to happen after another restart, and only stopped after removing UTime and restarting the server again.

I am now fairly confident UTime is the culprit but will continue to test.

It's worth noting that players on the 64bit branch of GMod did not experience this problem at all, or if they did, it was significantly less frequent.

I'll update this comment with any additional info I find.

**Comment by Nayruden** [comment]
A bit of a Hail Mary, but can you check if you have the issue using this version of UTime? https://github.com/thegrb93/utime/tree/patch-1

**Comment by sarahsturgeon** [comment]
I applied that patch to our fork - still waiting for a good time to restart to give it a test. Will update this thread as soon as we do!

**Comment by sarahsturgeon** [comment]
**Update:**

With Sparky (thegrb93)'s patch, we noticed that _fewer_ people were timing out, but still a non-0 number.

I've also all but confirmed that those affected are all using the base gmod branch.

I tried a little experiment with someone who was reliable timing out;
1. Made an exact copy of our darkrp server, put the `master` branch of UTime on, and started it
2. Had our reliable-crasher connect there instead (it was just him and I, no props or anything on the map)

**Results:**
The tester _did not_ crash. This threw me off because they have been timing out reliably ever since we added utime. They had tried joining at different points in the game - when there were no props but many players (right as it started), and when there were many props and players (after hours of gameplay).
I really expected them to have crashed at this point.

So, I was stumped. I can't use that server as a way to test because our testers aren't even crashing reliably anymore.

**As a result, take all of these outcomes with a grain of salt.**

After digging through the clientside code some more I realized that the `utime_enable` convar doesn't really do anything but show/hide the panel. All of the logic (the traces and so forth) was still being done even with the convar set to `0`.

On top of sparky's patch, [I also tried simply breaking out of the `think` function if the panel was supposed to be hidden](https://github.com/CFC-Servers/utime/blob/master/lua/autorun/cl_utime.lua#L45) (if the convar is set to `0`, or if the player is using the camera, etc.). My thinking was that if it was something to do with the logic, breaking out early and defaulting `utime_enable` to `0` could help the clients running on the base gmod branch.

I had our tester modify their `client.vdf` and `config.cfg` (just to be safe I guess?) to set `utime_enable 0` (with the proper formats for each file) to ensure that when they join, the convar would already be set to `0`.

Because I couldn't get any valid results on the test server, I took a risk and just threw it on our primary server where we regularly see 20-30 players.

After restarting, **our tester was able to join without issues.**

I had a group of our players spawn a bunch of dupes all over the map, spawn money printers, holograms, gun shipments, etc. Anything they could to quickly replicate what the server might look like (from a memory perspective) after hours of gameplay. While not a perfect test, it was the best we could do (I needed to know if I had to do another restart to remove UTime entirely ASAP before players got established).

Our tester kept restarting garry's mod and **rejoining successfully each time.**
_However_, other players who were also trying to join before and had been timing out **_were still timing out_**.

So, to me, this could mean that players who typically crashed while UTime was installed were joining with the default `utime_enable 1` and were still timing out, whereas our tester who definitely had it set to `0` was not.

Again, this is not a proper test and these results could be misleading, _but_ this could also mean that sparky's patch + my patch + a default of `utime_enable 0` could prevent this issue - at least for as long as it remains disabled.

For now, UTime is removed from the server and I have yet to see a single timeout (going for about 45m with ~35 joins).

I wish I had more definitive results to such a puzzling problem, but this is all I could gather today.
I'll keep looking into it as time allows.

**Comment by DeSavanger** [comment]
Thank god I found this issue. I had the same issue on my server; people joining were timed out with a 

> **Engine Error: Lua Panic! Something went horribly wrong! "not enough memory"**

error OR a 

> **Failed to lock vertex buffer in CMeshDX8::LockVertexBuffer: nVertexCount=174, nFirstVertex=0, nVertexSize=4, VertexFormat=8**

error. When you analyse there .mdmp file, you see the client console is spammed with 

> **Cbuf_AddText: buffer overflow**

I didn't believe them first (because I didn't had this error when connecting to my server), but after I've reset Garry's Mod to it's default (with **FactoryReset-GMod.bat**, located in your **steamapps\common\GarrysMod** folder) I had exact the same error. Even when Garry's Mod is crashing showing a window with no text in it, you can still press **CTRL+C** to copy the text, there you will see it throws the **LUA Panic: Not enough memory** error. I think it's due to the 32-bit version of Garry's Mod, because the RAM usage is going up to 3GB+ and then it crashes. It took me more then half of a day to find out what addon was causing the problem (I have 80+ addons installed), and finally I found this topic. All I can say is that @TeamUlysses really needs to update this addon and I've requested removal on the Steam Workshop. There indeed is a x64 beta branch for Garry's Mod and this indeed solves the problem, but it isn't a stable-branch yet, and if you're honest, this addon shouldn't take that much RAM for a stupid window. I've completely removed ULX, ULib, URS, UTime from my server, lol.

**Comment by Nayruden** [comment]
@WhiteSasch do you still have any problems using the patch thegrb93 pushed? It's definitely not a RAM issue from the addon's perspective. We think there's a bug in how GMod handles hooks for UI elements, but we've never been able to replicate the issue on our side.

**Comment by DeSavanger** [comment]
> @WhiteSasch do you still have any problems using the patch thegrb93 pushed? It's definitely not a RAM issue from the addon's perspective. We think there's a bug in how GMod handles hooks for UI elements, but we've never been able to replicate the issue on our side.

Well, I didn't try that patch... I will, later, maybe... Thanks for your info.

**Comment by moelrobi** [comment]
Can also just confirm @WhiteSasch on this topic. Had the same error on that regard happening to me.

**Comment by BlackCetha** [comment]
I can remember having this issue on my previous install, sometime around 2014. Just installed clean from master branch for testing and getting this in client console:
```
controlpanel.Get() - Error creating a ControlPanel!
You're calling this function too early! Call it in a hook!
Cbuf_AddText: buffer overflow (x14)

[ulib] vgui.Create failed to create the VGUI component (ControlPanel)
  1. Get - lua/includes/modules/controlpanel.lua:24
   2. resetCvars - addons/utime/lua/autorun/cl_utime.lua:330
    3. fn - addons/utime/lua/autorun/cl_utime.lua:360
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:109


Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 27	"Get"		lua/includes/modules/controlpanel.lua
	3: Line 330	"resetCvars"		addons/utime/lua/autorun/cl_utime.lua
	4: Line 360	"fn"		addons/utime/lua/autorun/cl_utime.lua
	5: Line 109	"nil"		addons/ulib/lua/ulib/shared/hook.lua
```

No crash though, but that could be because I'm on 64 bit.

**Comment by BlackCetha** [comment]
My initial guess is that hooking `OnEntityCreated` is too early (https://github.com/TeamUlysses/utime/blob/master/lua/autorun/cl_utime.lua#L363). Maybe try `PlayerInitialSpawn`?
